### ISSUE TITLE
Implementar processamento de marca d'água

### ISSUE THREAD

**Issue by stefanobaldo** [ingaia/CMS#1]
A requisição de alteração da marca d'água deverá ser enviada para uma fila de processamento

**Comment by stefanobaldo** [comment]
Se tiver alguma dúvida sobre o projeto da fila de marca d'água, imagino que o @kmkamonseki possa ajudar

**Comment by ocipro** [comment]
@rdrgmoraes 

Vou te manter atualizado sobre o desenvolvimento da marca d'agua a partir dessa issue. Irei comentando e te marcando aqui.

**Comment by stefanobaldo** [comment]
@rdrgmoraes Isto será desenvolvido após o MVP. A configuração da marca d'água (posicionamento) está funcionando normalmente. Caso o usuário modifique o arquivo da marca d'água este processo será disparado manualmente por enquanto. @jesse1983 ciente? Todos de acordo?

**Comment by rdrgmoraes** [comment]
@stefanobaldo, precisamos minimizar qualquer processo manual para o que foi desenvolvido no MVP, sugiro avaliarmos o esforço necessário e já incluirmos em nosso backlog, devo definir a prioridade desta atividade para que iniciemos os trabalhos tão breve o CMS esteja em uso por nossos clientes.

**Comment by stefanobaldo** [comment]
@rdrgmoraes, a tarefa já está no backlog, voltamos a conversar sobre isso tão logo o CMS esteja em uso - esta issue permanecerá aberta

**Comment by stefanobaldo** [comment]
Já está feito, mas após modificar a marca d'água precisa clicar em Resetar Marca D'Água no backoffice. Só falta automatizar isso - vou manter a issue aberta

**Comment by stefanobaldo** [comment]
Feito!
