### ISSUE TITLE
Mesmo colocando pra esconder o endereço, está mostrando

### ISSUE THREAD

**Issue by jesse1983** [ingaia/CMS#146]
http://aline_ferreira_campos.gaiasite.com.br/

**Comment by stefanobaldo** [comment]
@jesse1983: Não consegui reproduzir

<img width="329" alt="screen shot 2016-05-18 at 09 12 22" src="https://cloud.githubusercontent.com/assets/1918151/15358075/db10b7ac-1cd8-11e6-8089-f3e2239723da.png">

<img width="503" alt="screen shot 2016-05-18 at 09 12 33" src="https://cloud.githubusercontent.com/assets/1918151/15358078/e042f244-1cd8-11e6-842f-4428c5514641.png">

<img width="372" alt="screen shot 2016-05-18 at 09 12 51" src="https://cloud.githubusercontent.com/assets/1918151/15358084/e3ea299e-1cd8-11e6-81d2-e470cb0c7ff3.png">

<img width="329" alt="screen shot 2016-05-18 at 09 13 06" src="https://cloud.githubusercontent.com/assets/1918151/15358086/e73f6ab4-1cd8-11e6-84f8-0cc24e6f30c3.png">

<img width="473" alt="screen shot 2016-05-18 at 09 13 15" src="https://cloud.githubusercontent.com/assets/1918151/15358094/ee6f333c-1cd8-11e6-85f0-720e6f179639.png">

**Comment by jesse1983** [comment]
@rdrgmoraes Veja se está ok.

**Comment by rdrgmoraes** [comment]
@jesse1983, conseguimos inserir os números na barra azul? Podemos aumentar um pouco a altura dela e inserir neste local.

![image](https://cloud.githubusercontent.com/assets/17769443/15428019/6a4aeeaa-1e6f-11e6-8c54-cd46038c0e95.png)

**Comment by rdrgmoraes** [comment]
@jesse1983, só pra confirmar, as alterações foram realizadas conforme layout?
