### ISSUE TITLE
Trocar as cores de fundo do site

### ISSUE THREAD

**Issue by jesse1983** [ingaia/CMS#160]
@rdrgmoraes Definir as cores disponíveis de fundo

**Comment by rdrgmoraes** [comment]
@lucianonetto, sugiro aplicarmos como opção um tom de cinza, bem claro, alguma sugestão?

**Comment by lucianonetto** [comment]
Ou cores de tom pastel 
http://inesquecivelcasamento.s3.amazonaws.com/wp-content/uploads/2015/09/Paleta-de-cores-tons-pastel.jpg

ou texturas tipo nesse site http://demo.brankic.net/bigbangwp/

**Comment by rdrgmoraes** [comment]
@jesse1983, conseguimos aplicar estas cores indicadas pelo @lucianonetto?

**Comment by jesse1983** [comment]
@rdrgmoraes Só faltou ele indicar o rgb de cada uma...rs
Ok, irei pegá-las no photoshop. Só as cores e não as texturas?

**Comment by rdrgmoraes** [comment]
@jesse1983, se conseguirmos incluir também as texturas seria excelente...

**Comment by rdrgmoraes** [comment]
@jesse1983, precisamos deste item para o lançamento, temos muita procura por este tipo de mudança.
