### ISSUE TITLE
Criar modelo de página institucional

### ISSUE THREAD

**Issue by jesse1983** [ingaia/CMS#163]

**Comment by jesse1983** [comment]
@stefanobaldo Criei as chaves `PAGE.INSTITUCIONAL.CONTEUDO` (text) e  `PAGE.INSTITUCIONAL.FOTOS` (json). Com o HTML do @lucianonetto é necessário criar uma página que tenha slideshow do lado direito e texto do lado esquerdo, lendo as informações dessas chaves e do tipo de páginas modelo `INSTITUTIONAL`

**Comment by stefanobaldo** [comment]
Feito!
