### ISSUE TITLE
Adicionar busca nova no lugar da antiga

### ISSUE THREAD

**Issue by rdrgmoraes** [ingaia/CMS#168]
- Na homepage, ao realizar uma busca: Alugar, selecionar qualquer tipo e clicar sobre "bairro", trava e não carrega os bairros.

**Comment by stefanobaldo** [comment]
@rdrgmoraes Apenas confirmando, conforme discutido naquela última reunião que o Eduardo estava presente, vamos deixar somente a busca nova, certo? Outra coisa, hoje a busca nova é capaz de indexar os seguinte campos: `bairro`, `cidade`, `zona`, `empreendimento` e `logradouro`. Quais os campos serão o padrão para os sites CMS?

**Comment by rdrgmoraes** [comment]
@stefanobaldo: bairro, cidade e empreendimento.

**Comment by lucianonetto** [comment]
Feito e commitado, precisa ver a questão do id da agencia.

**Comment by stefanobaldo** [comment]
Feito
