### ISSUE TITLE
Melhorar a ficha de impressão 

### ISSUE THREAD

**Issue by jesse1983** [ingaia/CMS#169]
Existem vários problemas:
- Não tem a referência do imóvel
- Não tem informações de contato ou da imobiliária

**Comment by rdrgmoraes** [comment]
Acrescentar as informações listadas na issue, não tenho acréscimos. @jesse1983, você me marcou por causa do layout?

**Comment by jesse1983** [comment]
@rdrgmoraes Exato, é necessário fazer um novo layout porque aquele está bem _antiquado_

**Comment by rdrgmoraes** [comment]
@jesse1983, concordo mas não temos como fazer algo de imediato. Conseguimos fazer algo provisóriamente sobre os pontos listados na issue?

**Comment by jesse1983** [comment]
Estamos sempre prontos para `Lipstick on a pig` @rdrgmoraes
