### ISSUE TITLE
Criar planos Free/Premium

### ISSUE THREAD

**Issue by rdrgmoraes** [ingaia/CMS#171]
Manter ativo apenas:

- Visão geral;
- Páginas (sem botão para adicionar nova página);
- Aparência: Logotipo, cores e rodapé;
- Configurar: Ficha do imóvel, redes sociais, marca d'agua e captcha.

Obs.: O site deverá ser criado no wizard já com as vitrines e páginas padrões.

**Comment by jesse1983** [comment]
Pronto. Quando o CMS é acessado através do ambiente de homologacao, o sistema desconsidera se o usuário é FREE ou PREMIUM. Se acessado em produção, tudo é bloqueado. 

@rdrgmoraes Rodrigo, está pendente da tela de "Venda" do produto (#210).

@stefanobaldo Verifique se está faltando a parte da API, ok?
