### ISSUE TITLE
Conectar a um domínio

### ISSUE THREAD

**Issue by rdrgmoraes** [ingaia/CMS#172]
- Desenvolver tela para exibir informações para o usuário conectar um domínio ao site.

Antes de iniciar qualquer desenvolvimento, analisar formato da TecImob, precisamos de algo semelhante.

**Comment by jesse1983** [comment]
## Tecimob
![image](https://cloud.githubusercontent.com/assets/2489514/15683105/210ed3a2-2737-11e6-91cd-6ae193ad65b1.png)
=====
![image](https://cloud.githubusercontent.com/assets/2489514/15683120/2c2a4b72-2737-11e6-9e7b-3e4b40edc862.png)
=====
![image](https://cloud.githubusercontent.com/assets/2489514/15683133/37a6df74-2737-11e6-9a47-4521f86dfb5e.png)
=====
![image](https://cloud.githubusercontent.com/assets/2489514/15683149/46e4e97c-2737-11e6-8924-ab609a36ecc5.png)
=====
![image](https://cloud.githubusercontent.com/assets/2489514/15683161/57870f8a-2737-11e6-9b04-cc5516967be9.png)

**Comment by jesse1983** [comment]
@rdrgmoraes Veja se é isso que vc precisa:
https://xd.adobe.com/view/fe7ce844-0c3c-4e1c-663c-794f4b1e6e7e/

**Comment by rdrgmoraes** [comment]
@jesse1983, faltou apenas um último step, onde o CMS verifica e informa que a configuração está correta e foi feita com sucesso. Precisamos prever o cliente que irá alterar as entradas NS ou o cliente que irá fazer apontamento (vamos ter ambas as situações pois a princípio não teremos um painel próprio para alteração de zonas de DNS).

**Comment by jesse1983** [comment]
OK @rdrgmoraes .

@stefanobaldo para conectar do domínio, vou precisar de:

- [ ] Um endpoint que receba o domínio e ele me retorne informações se está disponível ou não, e outras informações disponíveis, como `/check-domain?domain=imobiliaria.com.br`. 

- [ ] Criar o enpoint `/websites/:id/domains` com POST/PUT/GET/DELETE. Sugestão para o objeto:
```javascript
{

   "id": 123,
   "created_at": "2016....",
   "registered_at": "2016....",
   "domain": "imobiliaria.com.br",
   "verified": false,
   "main": true
}
``` 

Sugestão:  https://whoisrb.org/ ou https://github.com/weppos/publicsuffix-ruby
