### ISSUE TITLE
Melhorar a aplicação da marca d'água

### ISSUE THREAD

**Issue by jesse1983** [ingaia/CMS#174]
- [x] Aplicar no `imagem.ashx` a proporção de 20% da imagem
- [x] Aplicar a mesma regra no processo background de marca d'água
- [x] Não aplicar marca d'água nos lançamentos

**Comment by stefanobaldo** [comment]
@jesse1983 @rdrgmoraes não será aplicada marca d'água em nenhuma imagem referente à lançamento ou condomínio? é isso?

**Comment by rdrgmoraes** [comment]
@stefanobaldo, a minha sugestão é que na configuração das vitrines o usuário consiga delimitar se ele quer que a marca d'agua seja aplicada (sim/não). Sempre que o usuário utiliza banners ao invés de fotos puras do imóvel, a aplicação da marca d'agua pode sobrepor a arte do banner e o aspecto final não é nada agradável.

**Comment by stefanobaldo** [comment]
@rdrgmoraes concordo, mas isso demandaria neste momento mais esforço além de tudo que já temos para fazer - na sua opinião é urgente a ponto de termos que incluir no MVP ou podemos escolher entre exibir ou não exibir neste primeiro momento? @jesse1983 ?

**Comment by rdrgmoraes** [comment]
@stefanobaldo, não é prioridade, podemos deixar sem a marca d'agua em lançamentos por padrão? Os sites atuais são assim.

**Comment by stefanobaldo** [comment]
@rdrgmoraes ok, vou verificar essa última questão da marca dagua amanhã e pode deixar no backlog a questao da opcao para voltarmos a discutir depois

**Comment by stefanobaldo** [comment]
@rdrgmoraes Rodrigo, estou olhando no VirtualGaia e nos sites atualmente em produção, e as fotos de lançamentos possuem marca d'água sim:

![screen shot 2016-06-05 at 00 04 16](https://cloud.githubusercontent.com/assets/1918151/15803390/382b26da-2ab1-11e6-848c-87e1c89a0622.png)

Talvez você tenha pensado em remover a marca d'água somente em imagens do tipo __banner__, que se encaixam em modelos específicos de vitrine que pegam a largura da tela quase toda, mas aí já é um pouco mais chato para fazer pois nós teríamos que deixar um código descaradamente condicional.

O correto seria parametrizar a exibição da marca d'água na configuração da vitrine, conforme você já havia colocado, mas isso já envolve um esforço maior em ambas as frentes e havíamos concordado em deixar para depois.

O que você quer fazer? Quer deixar de exibir marca d'água GERAL para todo e qualquer empreendimento (não é a realidade dos sites hoje), ou vamos deixar como está e discutirmos isso melhor depois?

**Comment by rdrgmoraes** [comment]
@stefanobaldo, atualmente possuimos dois padrões para a vitrine de lançamentos, uma para exibição sem marca d'agua, outra para exibição com marca d'agua. Note que no exemplo que você pegou, as imagens são mais quadradas e este padrão foi pensado justamente na exibição de condomínios verticais. Para o outro padrão, mais retangular (1140px de largura), a marca d'agua não é exibida, pois a vitrine foi especificamente planejada para banners. Por este motivo sugeri darmos a opção do usuário determinar se quer ou não a marca d'agua no módulo que controla as vitrines.

**Comment by stefanobaldo** [comment]
Ok, corrigido!
