### ISSUE TITLE
Listagem de imóveis não está aparecendo imóveis da rede

### ISSUE THREAD

**Issue by jesse1983** [ingaia/CMS#182]
Mensagem da Angela:
> http://www.bigtowerimoveis.com.br/  não está exibindo imóveis de locação da rede, no backoffice está configurado tudo certo,  ele é  da Rede Imóvel Certo, vejam um exemplo de outro cliente da mesma rede em que a busca funciona corretamente e inclusive exibe imóveis de locação desse cliente bigtowerimoveis.com.br : http://www.ctimoveis.com.br/listagem.aspx?ddlPretensao=2&cidade=0&ddlBairro=&bairro=&vlLocacao=0

**Comment by stefanobaldo** [comment]
bullshit
