### ISSUE TITLE
Comprar plugin Froala Editor

### ISSUE THREAD

**Issue by stefanobaldo** [ingaia/CMS#183]

**Comment by stefanobaldo** [comment]
@rdrgmoraes e aí cara, vai comprar ou não? 😝

**Comment by stefanobaldo** [comment]
@jesse1983 me ajuda a pressionar o cara aí

**Comment by jesse1983** [comment]
@rdrgmoraes Resolva!

**Comment by rdrgmoraes** [comment]
@stefanobaldo, já tenho a aprovação formalizada, era o que eu precisava, amanhã (sexta) vou comprar a licença.

**Comment by rdrgmoraes** [comment]
Licença adquirida, dados transmitidos para o @jesse1983
