### ISSUE TITLE
Imagem quebrada no slideshow do imóvel 

### ISSUE THREAD

**Issue by jesse1983** [ingaia/CMS#185]
Segue o imóvel que está com problema:

http://diego_luiz_rauber.gaiasite.com.br/imovel/apartamento-residencial-venda-locacao-cidade-nova-itajai-sc/ap0005/

Observe que quando clica na imagem quebrada, pula para a próxima:
![image](https://cloud.githubusercontent.com/assets/2489514/15906597/f56d730c-2d8f-11e6-80f2-47bc76807a66.png)

**Comment by lucianonetto** [comment]
Feito e commitado.
