### ISSUE TITLE
Texto de plantas está vindo duplicado

### ISSUE THREAD

**Issue by jesse1983** [ingaia/CMS#187]
http://diego_luiz_rauber.gaiasite.com.br/lancamento/valencia-fazenda-itajai/5404067/

Clicar em `Plantas` e para ver a legenda duplicada:
![image](https://cloud.githubusercontent.com/assets/2489514/15944141/8977c3cc-2e62-11e6-9fc2-d04a66e28a16.png)

**Comment by lucianonetto** [comment]
Feito e commitado.
