### ISSUE TITLE
Imóvel não é exibiddo no super destaque

### ISSUE THREAD

**Issue by rdrgmoraes** [ingaia/CMS#188]
http://www.casaecompanhiaimoveis.com.br/
ID = 53531140

**Comment by lucianonetto** [comment]
Acho que para esse super destaque funcionar tem que ter pelo menos 4 imóveis marcados, e esse cliente tem 3, tente marcando mais um imóvel.

**Comment by rdrgmoraes** [comment]
@lucianonetto, temos como exibir a partir de 1 imóvel? Este tipo de questão não fica transparente para o usuário e é mais um gerador de suporte.

**Comment by lucianonetto** [comment]
@rdrgmoraes para esse super destaque não, pois ele é 100% e só funciona com a quantidade certa de imóveis.

**Comment by rdrgmoraes** [comment]
@lucianonetto, neste caso sugiro inserirmos um feedback visual no próprio site informando que o número de imóveis é insuficiente para exibição da vitrine e o número de imóveis a mais necessários.

**Comment by stefanobaldo** [comment]
@rdrgmoraes Rodrigo, vou marcar isso como melhoria. Estamos trabalhando na parte de conectividade de domínio e outras coisas relevantes para o lançamento e vamos deixar essas coisas menores para depois, ok? @jesse1983 concorda?

**Comment by jesse1983** [comment]
@stefanobaldo concordo, mas não acho que nenhuma dessas soluções ainda é a melhor. Sou a favor de mostrar 1 só e com um "buraco" nos locais onde não tem imóvel. @lucianonetto existe essa possibilidade?

**Comment by rdrgmoraes** [comment]
@stefanobaldo, vou deixar esta atividade apenas com o @lucianonetto, vamos inserir um feedback visual para a imobiliária no próprio site por enquanto.

**Comment by stefanobaldo** [comment]
@lucianonetto Precisa de alguma coisa server-side ou você consegue fazer via JS?

**Comment by lucianonetto** [comment]
Vou fazer por js, @rdrgmoraes me envie a frase que deve aparecer por favor.

**Comment by stefanobaldo** [comment]
![unni](https://cloud.githubusercontent.com/assets/1918151/16051117/c59eb146-3234-11e6-9631-b96b27add7b9.jpg)

**Comment by lucianonetto** [comment]
Conforme orientação do jessé, quando o cliente tem menos de 3 imóveis como super destaque os mesmos são copiados, assim não será necessário sumir com o super destaque.
Feito e commitado.
