### ISSUE TITLE
Desabilitar site homologação (xpto.gaiasite.com.br) após publicação em outro domínio ou cancelamento do cliente

### ISSUE THREAD

**Issue by rdrgmoraes** [ingaia/CMS#212]

**Comment by stefanobaldo** [comment]
@rdrgmoraes Rodrigo, o site publicado já é cancelado automaticamente quando o cliente cancela. Sobre o site homologação, ele é um trial e portanto será automaticamente cancelado em 15 dias ou período que definirmos. Por enquanto não estamos cancelando os trials (xpto.gaiasite.com.br) depois de um determinado período porque o pessoal está construindo os sites com os clientes e fiquei com medo de começar a desativar sites que o pessoal de projetos está mexendo no momento. Pense como quer fazer e me avise, ok?

**Comment by rdrgmoraes** [comment]
@stefanobaldo, o melhor formato é: quando um determinado domínio é configurado como principal, devemos desativar o site de homologação.

**Comment by stefanobaldo** [comment]
não 
vamos lá 
seguinte
trial, deixa ativo apenas enquanto o trial estiver ativo
o trial venceu 
tira o site do xpto.gaiasite.com.br
este está fechado?
posso passar para o próximo caso?
deixa eu ler pera
ok entendi
fechado
Rodrigo Moraes (rodrigo.moraes@i-value.com.br, rodrigo.moraes@ingaia.com.br)
blz 
próximo cenário 
o cliente é "ativo"
o xpto.gaiasite.com.br deve ficar no ar apenas enquanto o cliente estiver neste status 
se ele estiver suspenso ou cancelado 
o site deve sair do ar 
fechado?
hum
fechado mas ainda nao ta assim
Rodrigo Moraes (rodrigo.moraes@i-value.com.br, rodrigo.moraes@ingaia.com.br)
blz 
tem que ficar 
rs
hum ta
ultimo caso... cliente publicou dominio
se o cliente publicou o dominio vou tirar o gaiasite.com.br do ar depois de 48h fechou?
Rodrigo Moraes (rodrigo.moraes@i-value.com.br, rodrigo.moraes@ingaia.com.br)
fechado
